---
# Application metadata
meta:
  name: demo_app
  title: Demo App
  description: A declarative FastAPI application 🎉
  version: 0.1.0

# Custom settings model
settings: demo_app.settings.AppSettings

# Declare providers
# A few providers are available to use directly
# It's quite easy to add new providers
providers:
  - quara.wiring.providers.structured_logging_provider
  - quara.wiring.providers.prometheus_metrics_provider
  - quara.wiring.providers.openid_connect_provider
  - quara.wiring.providers.openelemetry_traces_provider
  - quara.wiring.providers.cors_provider
  - quara.wiring.providers.debug_provider
# It's possible to add routers
routers:
  - demo_app.routes.issuer_router
  - demo_app.routes.nats_router
# Or hooks
hooks:
  - demo_app.hooks.issuer_hook
# Or tasks (not used in this example)
tasks: []
# It's also possible to declare default config file
config_file: ~/.quara.config.json
