---
# Application metadata
meta:
  name: demo_app
  title: Demo App
  description: A declarative FastAPI application 🎉
  package: fastapi-wire

# Custom settings model
settings: demo_app.settings.AppSettings

# Add providers to the application
providers:
  - wire.providers.logger.structured_logging_provider
  - wire.providers.metrics.prometheus_metrics_provider
  - wire.providers.oidc.openid_connect_provider
  - wire.providers.tracing.openelemetry_traces_provider
  - wire.providers.cors.cors_provider
  - wire.providers.debug.debug_provider

# It's possible to add routers
routers:
  - demo_app.routes.issuer_router
  - demo_app.routes.nats_router
  - demo_app.routes.demo.router

# Or hooks
hooks:
  # Custom hook
  - demo_app.hooks.issuer_hook
  # Hook available in wire package
  # 2 MongoDB hooks are available: 1 uses a pymongo client and the other an asyncio motor client
  - wire.hooks.mongo.motor_client_hook
  - wire.hooks.mongo.pymongo_client_hook
  # NATS hooks
  - wire.hooks.nats.nats_client_hook
# Or tasks (not used in this example)
tasks: []
# # It's also possible to declare default config file
# config_file: ~/.quara.config.json
